x=eval(input("enter the value of x:-"))
y=eval(input("enter the value of y:-"))
print("x&y:-",x&y)
print("x|y:-",x|y)
print("~x:-",~x)
print("x^y:-",x^y)
print("x<<1:-",x<<1)
print("x>>1:-",x>>1)
