a=eval(input("enter the value of a:-"))
b=eval(input("enter the value of b:-"))
print(a,"a>b",b, ":-",a>b)
print(a,"a<b",b, ":-",a<b)
print(a,"a>=b",b, ":-",a>=b)
print(a,"a<=b",b, ":-",a<=b)
print(a,"a==b",b, ":-",a==b)
print(a,"a!=b",b, ":-",a!=b)
